### ISSUE TITLE
When signing in with GitHub, first email is returned instead of primary one

### ISSUE THREAD

**Issue by localheinz** [SocalNick/ScnSocialAuth#176]
Have a look at this: https://github.com/hybridauth/hybridauth/pull/360.

**Comment by SocalNick** [comment]
@localheinz - this has been merged, however, there is an issue with HybridAuth 2.4.0 preventing me from bumping. I'll tag a release as soon as HybridAuth 2.4.1 is tagged.

**Comment by SocalNick** [comment]
Should now be available in ScnSocialAuth [1.17.0](https://github.com/SocalNick/ScnSocialAuth/releases/tag/1.17.0).
