### ISSUE TITLE
Update already registered user

### ISSUE THREAD

**Issue by lku** [SocalNick/ScnSocialAuth#182]
Hi, is there any way, how to update already registered user profile?

When user is registered, new entity is persisted in [insert method](https://github.com/SocalNick/ScnSocialAuth/blob/master/src/ScnSocialAuth/Authentication/Adapter/HybridAuth.php#L516) and `registerViaProvider` event triggered.
But when same user is authenticated with same provider, its profile is not updated. 

For example: I'll register with Facebook in some application through this module, my profile is saved. Then I'll change my email in Facebook profile and log in application again and this change is not reflected.

**Comment by SocalNick** [comment]
Hi @lku 

Sorry, this is not currently supported but sounds like a good feature. You would need to add an else here: https://github.com/SocalNick/ScnSocialAuth/blob/master/src/ScnSocialAuth/Authentication/Adapter/HybridAuth.php#L99

Would you like to try making a Pull Request and I'll review?

**Comment by lku** [comment]
@SocalNick Absolutely, I'll send you that PR tomorrow.

**Comment by lku** [comment]
@SocalNick: My first aproach in #183, what do you think?
