### ISSUE TITLE
Error on update in Composer

### ISSUE THREAD

**Issue by joao-gsneto** [SocalNick/ScnSocialAuth#187]
Plz solve this error! =X
$ ./../composer.phar update

  [RuntimeException]                                                                  
  Could not load package socalnick/scn-social-auth in http://packagist.org: [Unexpec  
  tedValueException] Could not parse version constraint >=1.2.2 <2.0.0: Invalid vers  
  ion string "1.2.2 <2.0.0"

**Comment by SocalNick** [comment]
Upgrade your composer:
```
composer self-update
```
