### ISSUE TITLE
Debug configuration for Hybrid_Auth

### ISSUE THREAD

**Issue by P0rnflake** [SocalNick/ScnSocialAuth#192]
Hi SocalNick,

at first I must say this module is great and it saves a lot of time. Thank you for the excellent work, especially for the integration with doctrine.

Today I got the module running for me after a lot of debugging. I discovered that the Hybrid_Auth library provides debugging mechanics by itself (http://hybridauth.sourceforge.net/userguide/Debugging_and_Logging.html) but you are unable to configure it though your modules configuration.

It would be nice if you could add the debug mode configuration to the modules configuration (maybe a local.php.dist) and pass it to Hybrid_Auth.

Thanks!

**Comment by SocalNick** [comment]
Great suggestion. Would you mind submitting a PR? You could add it to the [local config file](https://github.com/SocalNick/ScnSocialAuth/blob/master/config/scn-social-auth.local.php.dist). Then add the option, getter, and setter to the [ModuleOptions class](https://github.com/SocalNick/ScnSocialAuth/blob/master/src/ScnSocialAuth/Options/ModuleOptions.php). Finally, read the option in the [HybridAuthFactory](https://github.com/SocalNick/ScnSocialAuth/blob/master/src/ScnSocialAuth/Service/HybridAuthFactory.php).

**Comment by P0rnflake** [comment]
Sounds like a plan, I have never done a pull request before, but I will try my best. 
Is there anything I should be aware of, tests, documentation or something?

**Comment by stijnhau** [comment]
i think this issue is resolved an can be closed?
