### ISSUE TITLE
Connect with multiple services at once?

### ISSUE THREAD

**Issue by gabrielsomoza** [SocalNick/ScnSocialAuth#194]
Is it possible for a single user to connect with multiple services? It works within a single user session because the service authentications are stored in memory, but the following doesn't work:

1. Create a new user account by signing in with one of the services (e.g. Github).
2. Sign in to another service (e.g. Facebook) using the same mechanism.
3. I'm now connected to both services during this user session. There's only one user record in the database (user "A").
4. Logout from all services.
5. Login with Facebook. The login doesn't work: I'm NOT connected to the other service (Github) and a new user record is created in the database (user "B") instead of using user "A". 

I expected to be logged in with user "A" and be automatically connected to both Github and Facebook.

Is this use-case currently supported? If not, what kind of approach would you recommend to support it?

**Comment by gabrielsomoza** [comment]
Looks like when trying to connect to the second service its getting stuck here because the user already authenticated so it just exits: [`ZfcUser\Controller\UserController::authenticateAction`](https://github.com/ZF-Commons/ZfcUser/blob/master/src/ZfcUser/Controller/UserController.php#L155) (it reaches that point after a forward from `ScnSocialAuth\Controller\UserController::providerAuthenticateAction`)

Would it be a good idea to create a new endpoint to the ScnSocialAuth controller (e.g. `attach-provider/:provider`) by-passing the check for an already-authenticated user in ZfcUser? Or otherwise how would you approach this?

**Comment by gabrielsomoza** [comment]
If I manually add a row to the `user_providers` table linking the existing user with the secondary service then everything works as intended :) - so all we need it seems is an endpoint to forcefully authenticate and create that row..

**Comment by SocalNick** [comment]
@gabrielsomoza there's an add-provider route you can use to do what you want. It's not linked to, you'll have to create a custom view script that links a logged in user to the route.

**Comment by gabrielsomoza** [comment]
Ah, missed it. Thanks!
