### ISSUE TITLE
How to get user profile after authentication?

### ISSUE THREAD

**Issue by diogodomanski** [SocalNick/ScnSocialAuth#196]
Sorry by the newbie question....

I have a ZF2 project using ScnSocialAuth + ScnSocialAuthDoctrineORM. After authenticating with Facebook, how can I get access to user profile's data?

Thanks in advance

Diogo

**Comment by SocalNick** [comment]
The ServiceManager has been configured to provide access to the underlying HybridAuth object. Once you get the HybridAuth object, you can take advantage of its API to get the user profile.

**Comment by diogodomanski** [comment]
Thanks for your answer SocialNick. Could you please provide an example of getting HybridAuth object through ServiceManager from a controller?

**Comment by SocalNick** [comment]
```
$hybridAuth = $this->getServiceLocator()->get('HybridAuth');
// if the user is connected, authenticate will return an instance of the provider adapter
$adapter = $hybridAuth->authenticate('facebook');
if (!$adapter->isUserConnected()) {
    // do something sensible for a logged out user...
    return $this->redirect()->toRoute('some-logged-out-route');
}
$userProfile = $adapter->getUserProfile();
```

**Comment by diogodomanski** [comment]
That's exactly what I was looking for. Thank you very much.
