### ISSUE TITLE
How to redirect to custom route upon non-social registration

### ISSUE THREAD

**Issue by sergioperezf** [SocalNick/ScnSocialAuth#203]
Hi,
With ScnSocialAuth disabled, I can use the value of `login_redirect_route` to redirect users after a successful login/registration. When I enable ScnSocialAuth, the users are redirected upon social login/registration, as well as after non-social login, but not after a non-social (email and password) registration. I have also tried setting `use_redirect_parameter_if_present` to `true` and adding a `hidden` input on the register view template. How can I achieve this?

**Comment by SocalNick** [comment]
This is fixed by https://github.com/SocalNick/ScnSocialAuth/pull/204, correct? If so, I'll draft a new release with that PR.

**Comment by sergioperezf** [comment]
@SocalNick yes, it is. Thanks for accepting the PR.

**Comment by SocalNick** [comment]
https://github.com/SocalNick/ScnSocialAuth/releases/tag/1.17.1
