### ISSUE TITLE
Not redirecting after click on sign in facebook

### ISSUE THREAD

**Issue by SashaSansay** [SocalNick/ScnSocialAuth#205]
Hello! I have an issue with this module afte click on any login link i'm redirecting to http://myssite/scn-social-auth/hauth?hauth.start=Facebook&hauth.time=1430150822 and after I'm not redirecting anywhere. What the problem I have? P.S.: Sorry for my bad english

**Comment by SashaSansay** [comment]
I've found the solution! The problem was in my nginx config. 

was:    
location / { 
        try_files $uri $uri/ /index.php$querystring;
    } 
i've made
    location / { 
        try_files $uri $uri/ /index.php?$args;
    }

**Comment by timoziemann** [comment]
thanks for posting the answer :X
