### ISSUE TITLE
README with an abrupt end

### ISSUE THREAD

**Issue by Mr-Penguin** [SocalNick/ScnSocialAuth#207]
Hi!
First of all: sorry if that's not a real issue ...
In my feeling the README has a very abrupt end, at least for me (yes, I'm quiet new to all this).

I did all the steps in the README and struggle what to do next. My approch (1) is (obviously) wrong because I get an error (PHP Fatal error:  Call to a member function getEnabledProviders()).
I'd be happy to contribute to a better README but first I'll need your help to figure out where my thinking is wrong.

(1) I edited the zfc-user login.phtml and copy-pasted the stuff from vendor/socalnick/scn-social-auth/view/scn-social-auth/user/login.phtml

**Comment by juuce** [comment]
Hi, I too have something similar to this which is probably not 'an official issue' with the code but more so with a way of utilising this fantastic module. (also relatively new to zf2)
I've tried to customise my zfcuser routes to use 'account' instead of the default 'user' route of zfcuser. It seems that by using a custom route the ScnSocialAuth does not 'connect' to my custom route BUT it is still visible in the original (e.g. /user/register shows the social login section but /account/register does not)
It sounds like my lack of knowlegde in Zf2 is most likely the cause but I thought I'd go straight to the source and add my 2c since someone has already put a similar post up. Sorry if this mucks you around a bit.
If I try and override the view for ScnSocialAuth in my own module I get the same issue as Mr-Penguin above.
Mr-Penguin: it seems that you are calling $this->options->getEnabledProviders() where the options object is not defined or not injected...

**Comment by Mr-Penguin** [comment]
Hi juuce! Thanks for your 2c on the topic! I think I would've run into the same problem sooner or later, becuase I too plan to rename the /user/ ...
It's not defined, obviously, but I don't know why, because even if I go step by step with the README by using the SkeletonApp it won't run displaying the same error.
I hate to be a beginner in something . . .

**Comment by SocalNick** [comment]
Take a look at my sandbox app as an example: https://github.com/SocalNick/ScnSocialAuth-Sandbox

You can see it running here: http://scn-social-auth-sandbox.cfapps.io/user/login

**Comment by Mr-Penguin** [comment]
Hi Nick, thanks for posting this sandbox app.
When I try to run it (copy it, install stuff with composer, edit db credentials) I get tons of errors.
What I wonder: does your app overwrite standard zfc-login form? I'm just asking because in your sandbox app there's no login.phtml. 
Sorry if this is a dumb question to any expert, but I try to figure out where my thought process went in the wrong direction...

**Comment by SocalNick** [comment]
Yes it does: https://github.com/SocalNick/ScnSocialAuth/blob/master/view/scn-social-auth/user/login.phtml

Notice it doesn't add any social login buttons unless you have enabled those providers. Providers should be enabled in your apps `scn-social-auth.global.php` as shown in the sandbox app: https://github.com/SocalNick/ScnSocialAuth-Sandbox/blob/master/config/autoload/scn-social-auth.global.php#L38

**Comment by Mr-Penguin** [comment]
Thanks for your fast reply.
Will they only be added if I have a valid token from given provider?
I've enabled Facebook but don't have a valid token (yet). Will it still display it or not? Same for other networks.
And as a sidenote: I've read that, for example, Google API can not be run locally and needs an active connection to the internet. Will those enabled providers only show in /user/login if they will *actually* work?
I'm just asking because I've set up everything like you said, enabled the providers in the `scn-social-auth.global.php` and yet there're no providers showing.

**Comment by SocalNick** [comment]
Have you enabled the module?

https://github.com/SocalNick/ScnSocialAuth-Sandbox/blob/master/config/application.config.php#L6

**Comment by Mr-Penguin** [comment]
Yes kind sir, I have. It's really weird to me because I did everything I did with other modules before.
My `application.config.php` looks like that
``` 
 'modules' => array(
    'Application',
    'ScnSocialAuth',
    'ZfcBase',
    'ZfcUser',
     'TwbBundle',
    'ZfSnapJquery'`
...
```

**Comment by waddedMeat** [comment]
Try changing the order of your modules array...

```
 'modules' => array(
    'ZfcBase',
    'ZfcUser',
     'TwbBundle',
    'ZfSnapJquery'`
    'ScnSocialAuth',
    'Application',
```

This will allow the ZfcUser to override the ZfcBase, and ScnSocialAuth to override anything above it.

**Comment by Mr-Penguin** [comment]
Thanks for the advice with reordering but it still won't work. What really bugs me is the fact that it even won't work with the SkeletonApp set up. I'll try to install it on a different server, maybe that will (magically) work somehow.

**Comment by SocalNick** [comment]
Maybe try running my sandbox app instead of your code. You should be able to just download it, run `composer install` and start it.

https://github.com/SocalNick/ScnSocialAuth-Sandbox

**Comment by Mr-Penguin** [comment]
Ok, good(ish) news. I tried a whole different server and after some issues it finally works there.
I'll update this post as soon as I figured out what exactly the problem is with my other server.

**Comment by Mr-Penguin** [comment]
It's solved.
I'm new to Github, so I don't know if I have to close this issue? We might need to adjust the Readme (see above). Thanks guys.

**Comment by SocalNick** [comment]
The README clearly states to copy `./vendor/socalnick/scn-social-auth/config/scn-social-auth.global.php.dist` to `./config/autoload/scn-social-auth.global.php`. 

This is a very common pattern for ZF2 modules.

**Comment by juuce** [comment]
Hi, Sorry to open this again but it is a related comment/question.

My issue was that I was overwriting the ZFcUser entity and route from 
<domain>/user/ to <domain>/account/
    'zfcuser' => array(
             // telling ZfcUser to use our own class
             'user_entity_class'       => 'WMember\Entity\WMember',
             // telling ZfcUserDoctrineORM to skip the entities it defines
             'enable_default_entities' => false,
             'table_name' => 'w_member',
             'login_redirect_route' => 'account',
     ),

'template_map' => array(
             'zfc-user/user/login' => __DIR__ . 
'/../view/zfc-user/user/login.phtml',    // ZFC User
             'error/403' => __DIR__ . 
'/../view/bjy-authorize/error/403.phtml',            // BJY-Authorise
             //'scn-social-auth/user/register' => __DIR__ . 
'/../view/scn-social-auth/user/register.phtml',    // ScnSocialAuth
             //'zfc-user/user/register' => __DIR__ . 
'/../view/scn-social-auth/user/register.phtml',    // ZFC User
         ),

It seems that the config in the file has a 'route' key which is set to 
user and therefore my Social login button did not work when using my 
custom /account/ route.

  'scn-social-auth-user' => array(
                 'type' => 'Literal',
                 'priority' => 2000,
                 'options' => array(
                     'route' => '/user',
                     'defaults' => array(
                         'controller' => 'zfcuser',
                         'action'     => 'index',
                     ),
                 ),

Is there a configuration way to adjust this within my module (is it even 
possible)?
OR am I just doing something that is stupid and not required? I would 
guess that I only need the social plugin links on registration and login 
and no other pages it would be required...

Any pointers at this point are appreciated.

Cheers,

**Comment by CasperF** [comment]
Overwrite the route, make sure your application module is loaded after ScnSocialAuth (place it beneath in the application config module array).

**Comment by juuce** [comment]
Thank you.
I did this following my email. Standard ZF2 process so my fault. Sorry 
to bug you about it.
I am however still having issues with the returning call from facebook 
where I'[m getting page warnings "Array to string conversion" in 
Zend\Db\Adapter\Driver\Pdo\Statement.php on line/293/
/user/authenticate/facebook#_=_


      Zend\Db\Adapter\Exception\InvalidQueryException

Statement could not be executed (42S22 - 1054 - Unknown column 'array_copy' in 'field list')


It must be my fault as I've installed a fresh version of zf2 skeleton 
with your module and this seems to be OK.
I am using a custom entity to extend zfcuser with new fields in must 
custom named table...
Anyway, if you have any ideas please let me know. I know this is not a 
support forum so if you don't have time please ignore this email.

Cheers,

Dave

**Comment by juuce** [comment]
Thanks, regarding my previous email the issue was with the Newly defined 
Entity using getArrayCopy() as a method within the entity... My fault 
again...
