### ISSUE TITLE
Social Login issue.

### ISSUE THREAD

**Issue by Ajay17** [SocalNick/ScnSocialAuth#208]
How can I login with google . I mean to say what is the url for social login. I have type this url /public/user/add-provider/google but it give 404 error. Please help me.

**Comment by SocalNick** [comment]
Take a look at my sandbox app as an example: https://github.com/SocalNick/ScnSocialAuth-Sandbox

You can see it running here: http://scn-social-auth-sandbox.cfapps.io/user/login

**Comment by SocalNick** [comment]
Closing since no response
