### ISSUE TITLE
Facebook access token

### ISSUE THREAD

**Issue by CasperF** [SocalNick/ScnSocialAuth#211]
Not sure if this is a hybridauth issue or ScnSocialAuth, but wouldn't it be useful to be able to save the access token from a logged in user into the database as soon as he logs in? And be able to exchange it for an extended access token?

**Comment by CasperF** [comment]
Hmm seems hybridauth is using a very old version of the Facebook PHP SDK...

**Comment by SocalNick** [comment]
Can you file an issue with HybridAuth?
