### ISSUE TITLE
ZfcUser + DoctrineORM + BjyAuthorize + ScnSocialAuth

### ISSUE THREAD

**Issue by valexkeepcalm** [SocalNick/ScnSocialAuth#215]
Hi all. I've got ZfcUser/Doctrine/BjyAuthorize and it works fine. Next I installed ScnSocialAuth and HybridAuth and now when I try to access to social url like app/user/login/facebook I get the usual 404 error: 

A 404 error occurred Page not found.The requested controller was unable to dispatch the request.Controller:ScnSocialAuth-User. No Exception available

My application.config.php looks like:

'modules' => array(
        'DoctrineModule',
        'DoctrineORMModule',
        'ZfcBase',
        'ZfcUser',
        'ZfcUserDoctrineORM',
        'ScnSocialAuth',
        'BjyAuthorize',
        'Application',
        'User',
    ),

I created custom User Entity over ZfcUser. Who knows how to fix it?
Thanks.

**Comment by halesk** [comment]
Hi,

What is your solution for this? Did you use ScnSocialAuthDoctrineORM?

**Comment by valexkeepcalm** [comment]
Hi. No, I used ZfcUserDoctrineORM only. I will try the
ScnSocialAuthDoctrineORM. Thanks.
