### ISSUE TITLE
 An alias “ScnSocialAuth_ZendSessionManager” was requested but no service could be found

### ISSUE THREAD

**Issue by andreea120** [SocalNick/ScnSocialAuth#217]
I installed  ScnSocialAuth_ZendSessionManager into my zend 2 application. i am getting the following error message when i try to go to the login or registration page:

An alias "ScnSocialAuth_ZendSessionManager" was requested but no service could be found.

i have followed the instructions on your page and first uploaded it to project via composer.

i then install

./vendor/socalnick/scn-social-auth/config/scn-social-auth.global.php.dist
/vendor/socalnick/scn-social-auth/config/scn-social-auth.local.php.dist

to my config.

Then within the scn-social-auth.global.php i did the following:

$settings = array(

    'zend_db_adapter' => 'Zend\Db\Adapter\Adapter',

    'zend_session_manager' => 'Zend\Session\SessionManager'
}
);

return array(
    'scn-social-auth' => $settings,
    'service_manager' => array(
        'aliases' => array(
            'ScnSocialAuth_ZendDbAdapter' => (isset($settings['zend_db_adapter'])) ? $settings['zend_db_adapter']: 'Zend\Db\Adapter\Adapter',
            'ScnSocialAuth_ZendSessionManager' => (isset($settings['zend_session_manager'])) ? $settings['zend_session_manager']: 'Zend\Session\SessionManager',
        ),
    ),
);

i also created a ./config/autoload/session.local.php:

return array(
    'service_manager' => array(
        'invokables' => array(
            'Zend\Session\SessionManager' => 'Zend\Session\SessionManager',
        ),
    ),
); 

i also added the module to composer:

"require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "2.*",
        "socalnick/scn-social-auth": "1.*"
    }

so, i am unclear why i am still getting the error message;

would really appreciate any advise on this.

**Comment by andreea120** [comment]
this is my stack trace: 
#0 C:\wamp\www\testNewZend\vendor\socalnick\scn-social-auth\src\ScnSocialAuth\Service\HybridAuthFactory.php(27): Zend\ServiceManager\ServiceManager->get('ScnSocialAuth_Z...')
#1 [internal function]: ScnSocialAuth\Service\HybridAuthFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'hybridauth', 'HybridAuth')
#2 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(939): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'hybridauth', 'HybridAuth')
#3 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(1097): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'hybridauth', 'HybridAuth')
#4 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(638): Zend\ServiceManager\ServiceManager->createFromFactory('hybridauth', 'HybridAuth')
#5 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('HybridAuth', 'hybridauth')
#6 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#7 C:\wamp\www\testNewZend\vendor\socalnick\scn-social-auth\src\ScnSocialAuth\Service\UserControllerFactory.php(32): Zend\ServiceManager\ServiceManager->get('HybridAuth')
#8 [internal function]: ScnSocialAuth\Service\UserControllerFactory->createService(Object(Zend\Mvc\Controller\ControllerManager), 'scnsocialauthus...', 'ScnSocialAuth-U...')
#9 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(939): call_user_func(Array, Object(Zend\Mvc\Controller\ControllerManager), 'scnsocialauthus...', 'ScnSocialAuth-U...')
#10 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php(284): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'scnsocialauthus...', 'ScnSocialAuth-U...')
#11 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php(242): Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback(Array, 'scnsocialauthus...', 'ScnSocialAuth-U...')
#12 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(638): Zend\ServiceManager\AbstractPluginManager->createFromFactory('scnsocialauthus...', 'ScnSocialAuth-U...')
#13 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('ScnSocialAuth-U...', 'scnsocialauthus...')
#14 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#15 C:\wamp\www\testNewZend\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('ScnSocialAuth-U...', false)
#16 C:\wamp\www\testNewZend\vendor\zendframework\zend-mvc\src\Controller\ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('ScnSocialAuth-U...', Array, false)
#17 C:\wamp\www\testNewZend\vendor\zendframework\zend-mvc\src\DispatchListener.php(76): Zend\Mvc\Controller\ControllerManager->get('ScnSocialAuth-U...')
#18 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 C:\wamp\www\testNewZend\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 C:\wamp\www\testNewZend\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 C:\wamp\www\testNewZend\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 C:\wamp\www\testNewZend\public\index.php(21): Zend\Mvc\Application->run()
#23 {main}

**Comment by SocalNick** [comment]
Please take a look at my Sandbox application, it shows a working configuration:

https://github.com/SocalNick/ScnSocialAuth-Sandbox/blob/master/config/autoload/global.php#L46
https://github.com/SocalNick/ScnSocialAuth-Sandbox/blob/master/config/autoload/scn-social-auth.global.php#L194
