### ISSUE TITLE
Fatal error: Class 'Hybrid_Auth' not found

### ISSUE THREAD

**Issue by padalec** [SocalNick/ScnSocialAuth#221]
Hi there, 
I whant to try your plugin but I have problem when I tryu to integrate with my application. I can't install via composer so I add this pice of code to ZF lodaer:
```
Zend\Loader\AutoloaderFactory::factory([
    '!Zend\Loader\StandardAutoloader' => [
         'autoregister_zf'     => false,
         'fallback_autoloader' => true,
          'namespaces' => [
              'Hybrid' => __DIR__ . 'vendor/hybridauth/hybridauth/hybridauth/',
            
          ]
      ]
  ]);
```
But this doesn't work I have error below:
**Fatal error: Class 'Hybrid_Auth' not found in vendor/ScnSocialAuth/src/ScnSocialAuth/Service/HybridAuthFactory.php on line 34**
Thanks!

**Comment by SocalNick** [comment]
Sorry, I cannot support custom auto loading and dependency resolution. Composer is fairly standard, not sure why you can't use it?

**Comment by padalec** [comment]
Because app what I devlop right now don't have composer integration :/
