### ISSUE TITLE
Update ZfcUser to 1.4.1

### ISSUE THREAD

**Issue by manu777** [SocalNick/ScnSocialAuth#224]
You use a old version of ZfcUser in your composer.json. can you update it to 1.4.1?
best regards

**Comment by sOOrf** [comment]
stable 1.4.2

**Comment by kersten** [comment]
any news on this?

**Comment by manu777** [comment]
No i think the developer is inactive :(

**Comment by SocalNick** [comment]
Sorry, I'm not finding time to work on ScnSocialAuth. Maybe somebody in the community would like commit access to do the work?

**Comment by kersten** [comment]
Ok that's fine, you got time for merging pull requests?

**Comment by SocalNick** [comment]
Sorry for the delay...
