### ISSUE TITLE
How to perform a custom action after register?

### ISSUE THREAD

**Issue by Ge0hGM** [SocalNick/ScnSocialAuth#225]
Hi! everyone. I am using ZfcuserDoctrine + BjyAuthorize + ScnSocialAuth, so I want to add a role and other data, after user registration. I read this issue #159  , but I couldn't do it well. I always get this error "Uncaught exception 'Zend\Stdlib\Exception\InvalidCallbackException' with message 'Invalid callback provided; not callable'".  Could you please help me?

**Comment by stijnhau** [comment]
Wat is exactly the code you placed and where?

**Comment by SocalNick** [comment]
Closing due to no response
