### ISSUE TITLE
Manual setup steps - Zend Application

### ISSUE THREAD

**Issue by isreehari** [SocalNick/ScnSocialAuth#227]
Firstly thank you some much for the script, I am new to zend and recently I came across the a HRMS ( system for HR management) named as Sentrifugo and it's doing damn good stuff. I would like to add HybridAuth to this project. The file architecture of project is little different than all other zend projects. I am just wondering how to add your library to this project. Please give me some guidance. I am attaching the file structure of Sentrifugo project. 
![sentrifugo-file-structure](https://cloud.githubusercontent.com/assets/3519250/13697133/fae65c72-e730-11e5-81ba-1681c52a5b1e.jpg)

**Comment by isreehari** [comment]
Damn, I night out has paid off. I got it. Thanks for lib. Please close bug.

**Comment by isreehari** [comment]
Damn, My night out has paid off. I got it. Thanks for lib. Please close bug.

**Comment by stijnhau** [comment]
@SocalNick 
Can you close this?
