### ISSUE TITLE
ServiceLocatorAwareInterface is depracated

### ISSUE THREAD

**Issue by kusmierz** [SocalNick/ScnSocialAuth#230]
As of zendframework/zendframework#6068, ServiceLocatorAwareInterface is depracated, but this modules uses this interface in `src/ScnSocialAuth/Controller/Plugin/ScnSocialAuthProvider.php`.

**Comment by SocalNick** [comment]
Hi @kusmierz,

It appears it is still available in ZF2, which is what this module targets: https://github.com/zendframework/zend-servicemanager/blob/release-2.7.6/src/ServiceLocatorAwareInterface.php

I'm not really involved in the ZF community, I'm not sure that ZF3 is actually GA yet. I also have no plans of trying to make this module compatible with ZF3.
