### ISSUE TITLE
While attempting to create zendrouterroutepluginmanager(alias: Zend\Router\RoutePluginManager) an invalid factory was registered for this instance type.

### ISSUE THREAD

**Issue by gandhipranav** [SocalNick/ScnSocialAuth#232]
Hello,

I am getting below service manager issue

Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotCreatedException' with message 'While attempting to create zendrouterroutepluginmanager(alias: Zend\Router\RoutePluginManager) an invalid factory was registered for this instance type.' in C:\xampp\htdocs\Projects\lab2\vendor\zendframework\zend-servicemanager\src\ServiceManager.php:1096 Stack trace: #0 C:\xampp\htdocs\Projects\lab2\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(634): Zend\ServiceManager\ServiceManager->createFromFactory('zendrouterroute...', 'Zend\\Router\\Rou...') #1 C:\xampp\htdocs\Projects\lab2\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(597): Zend\ServiceManager\ServiceManager->doCreate('Zend\\Router\\Rou...', 'zendrouterroute...') #2 C:\xampp\htdocs\Projects\lab2\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array) #3 C:\xampp\htdocs\Projects\lab2\vendor\zendframework\zend-modulemanager\src\Listener\ServiceListener.php(208): Z in C:\xampp\htdocs\Projects\lab2\vendor\zendframework\zend-servicemanager\src\ServiceManager.php on line 1096

**Comment by SocalNick** [comment]
This doesn't appear to be related to this module.
