### ISSUE TITLE
ServiceLocatorAwareInterface is deprecated

### ISSUE THREAD

**Issue by shinesoftware** [SocalNick/ScnSocialAuth#234]
hi guys, 

I have this issue on your controller:

> Deprecated: You are retrieving the service locator from within the class ScnSocialAuth\Controller\UserController. Please be aware that ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. You will need to update your class to accept all dependencies at creation, either via constructor arguments or setters, and use a factory to perform the injections. in /vendor/zendframework/zend-mvc/src/Controller/AbstractController.php on line 258

How have I to solve it?

thanks

**Comment by SocalNick** [comment]
Fixed in https://github.com/SocalNick/ScnSocialAuth/releases/tag/1.19.1
