### ISSUE TITLE
An exception was raised while creating "ScnSocialAuth-User"; no instance returned

### ISSUE THREAD

**Issue by CallumBrankin** [SocalNick/ScnSocialAuth#240]
I'm getting this exception: An exception was raised while creating "ScnSocialAuth-User"; no instance returned

> #0 C:\xampp\htdocs\Zend2\path\to\install\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php(330): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'scnsocialauthus...', 'ScnSocialAuth-U...')
> #1 C:\xampp\htdocs\Zend2\path\to\install\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php(287): Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback(Array, 'scnsocialauthus...', 'ScnSocialAuth-U...')
> #2 C:\xampp\htdocs\Zend2\path\to\install\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(634): Zend\ServiceManager\AbstractPluginManager->createFromFactory('scnsocialauthus...', 'ScnSocialAuth-U...')
> #3 C:\xampp\htdocs\Zend2\path\to\install\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(597): Zend\ServiceManager\ServiceManager->doCreate('ScnSocialAuth-U...', 'scnsocialauthus...')
> #4 C:\xampp\htdocs\Zend2\path\to\install\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
> #5 C:\xampp\htdocs\Zend2\path\to\install\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php(161): Zend\ServiceManager\ServiceManager->get('ScnSocialAuth-U...', true)
> #6 C:\xampp\htdocs\Zend2\path\to\install\vendor\zendframework\zend-mvc\src\DispatchListener.php(94): Zend\ServiceManager\AbstractPluginManager->get('ScnSocialAuth-U...')
> #7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
> #8 C:\xampp\htdocs\Zend2\path\to\install\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
> #9 C:\xampp\htdocs\Zend2\path\to\install\vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> #10 C:\xampp\htdocs\Zend2\path\to\install\vendor\zendframework\zend-mvc\src\Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
> #11 C:\xampp\htdocs\Zend2\path\to\install\public\index.php(17): Zend\Mvc\Application->run()
> #12 {main}

**Comment by SocalNick** [comment]
It's difficult to understand the issue without more context. When does this occur? What are the parameters being passed when the stack trace is generated `Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'scnsocialauthus...', 'ScnSocialAuth-U...')`?

**Comment by CallumBrankin** [comment]
Nevermind i didn't install it properly
