### ISSUE TITLE
Support: always redirects to login page

### ISSUE THREAD

**Issue by thomascharbit** [SocalNick/ScnSocialAuth#242]
Hi,

I am asking here for some help, i implemented ScnSocialAuth with Facebook, but everytime a user try to log in he is redirected back to the login page instead.

It appears that in `UserController.php` [providerAuthenticateAction()](https://github.com/SocalNick/ScnSocialAuth/blob/master/src/ScnSocialAuth/Controller/UserController.php#L152) the hybridAuth property is empty, which explains the redirect.

I try to understand why this happen, but i don't really know where to start, the comment in code says "This is likely user that cancelled login..." but this is clearly not the case.

Any idea where i should have a look?

thanks!

**Comment by SocalNick** [comment]
Seems like something might be wrong with your service configuration. I don't use this module very often, so you'll have to do some digging on your end:

1. The HybridAuth get's [injected into the UserController here](https://github.com/SocalNick/ScnSocialAuth/blob/4f97a7930d293cb5aa592252ee72e9ccb858cf46/src/ScnSocialAuth/Service/UserControllerFactory.php#L37), see if it's null or throwing an exception.
1. The [HybridAuth is created via factory](https://github.com/SocalNick/ScnSocialAuth/blob/4f97a7930d293cb5aa592252ee72e9ccb858cf46/src/ScnSocialAuth/Service/HybridAuthFactory.php#L23), this is likely where you'll want to debug.

**Comment by thomascharbit** [comment]
Thanks, i was using an old version with incompatible Facebook SDK.
