### ISSUE TITLE
I cant integrate please help

### ISSUE THREAD

**Issue by sandeepsinghrules** [SocalNick/ScnSocialAuth#65]
I have exactly the same issue

https://github.com/SocalNick/ScnSocialAuth/issues/11

I have also checked the solution given by you multiple times in my project . Everything is exactly the same.

I have one doubt do i need to install the hybridauth seprately or its included in this mod.

I have seen the requirements where hybridauth is written, but i am confused as no proper help is provided for hybridauth. This mod is aewsome, but just cant get it working.

I am working with zf2 + Doctrine2.  Please help me out at this step.

I have installed 

'Application',
'ScnSocialAuth',
'ZfcBase',
'ZfcUser',
'DoctrineModule',
'DoctrineORMModule',
'Album',
'ZfcUserDoctrineORM',

Thanks
Sandeep

**Comment by Ajay17** [comment]
How can I login with google . I mean to what is the url for social login. I have type this url /public/user/add-provider/google but it give 404 error. Please help me.
